spring:
  h2:
    console.enabled: true
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
#    url: jdbc:h2:file:./data/demo
    username: sa
    password: 1234
    driverClassName: org.h2.Driver